### ISSUE TITLE
Run script fails on OSX from carriage-return

### ISSUE THREAD

**Issue by pablo-mayrgundter** [awv-informatik/buerligons#1]
Just cloned and yarn installed and then went to run the demo (after downloading the demo binary).

```
~/buerligons> yarn classcad
yarn run v1.22.10
$ classcad --ip localhost --port 8182 --instances 5 --ccappfile ./BaseModeling.ccapp
env: node\r: No such file or directory
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

but works fine with:

```
npm run dev
```

Looks to be just a Windows CRLF somewhere

**Comment by pablo-mayrgundter** [comment]
Found it by searching:

```
grep 'env node\r' -rl node_modules
```

the first match looked promising, so converted it:

```
```

**Comment by dm385** [comment]
Have you started the ClassCAD server in Docker as described in https://www.npmjs.com/package/@classcad/linux-x64? There are no binaries for OSX. ClassCAD is available for Windows/Linux. Under MAC it will only work via Docker.

**Comment by pablo-mayrgundter** [comment]
Yeah, I think this was it.  Been fine since running with Docker.  Thanks for updating the docs!
