### ISSUE TITLE
File load fails on both example files (Clamd.of1, Fusion.of1)

### ISSUE THREAD

**Issue by pablo-mayrgundter** [awv-informatik/buerligons#2]
Also tried it on another local STEP file and same error.  This is with new install just now (03cbcd15c350eebcb8c2c483ac75f52d1c81651d), demo binary 0.0.0-beta.8 and on OSX.

![image](https://user-images.githubusercontent.com/2480879/140303162-4b1267d7-fe6b-4c02-91f7-4786d2cbf5c7.png)

**Comment by pablo-mayrgundter** [comment]
Ah, missed that it needs the classcad server running, but yeah, blocked on #1.. I'll go fishing for it.

**Comment by dm385** [comment]
@pablo-mayrgundter please let us know, if this is still an issue after https://github.com/awv-informatik/buerligons/issues/1 is solved.

**Comment by drcmda** [comment]
I am using it on a M1 and, for the time being, have to use the amd container

```docker
FROM amd64/ubuntu:18.04
```

**Comment by pablo-mayrgundter** [comment]
Yep, I got these running after #1.  Thanks!
